export const facilData = [
  {
    id: 1,
    title: "Main Library",
    img: "https://images.pexels.com/photos/256417/pexels-photo-256417.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    type: "Library",
    floor: 1,
    openHours: "8:00 AM - 8:00 PM",
    location: "Building A",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 2,
    title: "Engineering Lab",
    img: "https://images.pexels.com/photos/256430/pexels-photo-256430.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    type: "Laboratory",
    floor: 3,
    openHours: "9:00 AM - 5:00 PM",
    location: "Building C",
    latitude: 52.4862,
    longitude: -1.8904,
  },
  {
    id: 3,
    title: "Student Canteen",
    img: "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    type: "Cafeteria",
    floor: 1,
    openHours: "7:00 AM - 6:00 PM",
    location: "Building D",
    latitude: 53.4808,
    longitude: -2.2426,
  },
  {
    id: 4,
    title: "Auditorium",
    img: "https://images.pexels.com/photos/167300/pexels-photo-167300.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    type: "Event Hall",
    floor: 2,
    openHours: "8:00 AM - 8:00 PM",
    location: "Building B",
    latitude: 53.8008,
    longitude: -1.5491,
  },
  {
    id: 5,
    title: "Physics Lab",
    img: "https://images.pexels.com/photos/256412/pexels-photo-256412.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    type: "Laboratory",
    floor: 2,
    openHours: "9:00 AM - 5:00 PM",
    location: "Building C",
    latitude: 53.4084,
    longitude: -2.9916,
  },
  {
    id: 6,
    title: "Gymnasium",
    img: "https://images.pexels.com/photos/3733924/pexels-photo-3733924.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    type: "Sports Center",
    floor: 1,
    openHours: "6:00 AM - 10:00 PM",
    location: "Building E",
    latitude: 54.9783,
    longitude: -1.6174,
  },
  {
    id: 7,
    title: "Computer Science Lab",
    img: "https://images.pexels.com/photos/391295/pexels-photo-391295.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    type: "Laboratory",
    floor: 4,
    openHours: "8:00 AM - 6:00 PM",
    location: "Building C",
    latitude: 53.3811,
    longitude: -1.4701,
  },
  {
    id: 8,
    title: "Campus Health Center",
    img: "https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    type: "Health Center",
    floor: 1,
    openHours: "8:00 AM - 4:00 PM",
    location: "Building F",
    latitude: 51.4545,
    longitude: -2.5879,
  },
];

export const singlePostData = {
  id: 1,
  title: "Main Library",
  location: "Mabini Building, 3rd Floor",
  openHours: "8:00 AM - 8:00 PM",
  images: [
    "https://images.pexels.com/photos/256417/pexels-photo-256417.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/167300/pexels-photo-167300.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/214387/pexels-photo-214387.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/169330/pexels-photo-169330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  ],
  latitude: 51.5074,
  longitude: -0.1278,
  type: "Library",
  floor: 3,
  nearbyFacilities: {
    canteen: "100m away",
    restroom: "50m away",
    lobby: "200m away",
  },
  description:
    "The Main Library offers a vast collection of resources for students and faculty. With multiple reading areas, a computer lab, and study rooms, it provides a quiet, resourceful environment for research and study. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
};

export const ownerData = {
  id: 1,
  name: "FAITH Colleges",
  img: "https://scontent.fmnl13-1.fna.fbcdn.net/v/t39.30808-6/458551987_936356025202828_6764137684277803772_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=3NkyDoMv5yoQ7kNvgEmCbLz&_nc_zt=23&_nc_ht=scontent.fmnl13-1.fna&_nc_gid=A3_Y-cV_rxPfJSDLPirhGCi&oh=00_AYA7dR1fARoHDI6KHfBgLnRJWgOHkIJrbRgTsAZ7GWPzLw&oe=67388EB4",
  fb: "https://www.facebook.com/FAITHColleges",
};

export const eventsData = [
  {
    id: 1,
    title: "Book Fair 2024",
    location_id: 1,
    date: "2024-11-15",
    time: "9:00 AM - 5:00 PM",
    img: "https://images.pexels.com/photos/583121/pexels-photo-583121.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description:
      "An exciting book fair featuring thousands of books across different genres. Meet local authors and take part in book signing sessions. A great opportunity for students and book lovers alike!",
  },
  {
    id: 2,
    title: "Engineering Workshop",
    location_id: 1,
    date: "2024-11-18",
    time: "10:00 AM - 3:00 PM",
    img: "https://images.pexels.com/photos/256219/pexels-photo-256219.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description:
      "Hands-on workshop covering key engineering concepts. Learn about robotics, circuit design, and much more. Open to all students in the engineering and technology departments.",
  },
  {
    id: 3,
    title: "Health and Wellness Seminar",
    location_id: 1,
    date: "2024-11-07",
    time: "1:00 PM - 3:00 PM",
    img: "https://images.pexels.com/photos/2377166/pexels-photo-2377166.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description:
      "A seminar focused on health and wellness for students and staff. Topics include mental health awareness, stress management, and physical wellness. Attendees will receive a free wellness kit.",
  },
  {
    id: 4,
    title: "Science Exhibit",
    location_id: 1,
    date: "2024-11-12",
    time: "9:00 AM - 4:00 PM",
    img: "https://images.pexels.com/photos/256401/pexels-photo-256401.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description:
      "Explore the world of science through interactive exhibits and experiments. The event will feature demonstrations in physics, chemistry, and biology with hands-on activities for attendees.",
  },
  {
    id: 5,
    title: "Sports Fest",
    location_id: 1,
    date: "2024-11-09",
    time: "8:00 AM - 6:00 PM",
    img: "https://images.pexels.com/photos/595747/pexels-photo-595747.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description:
      "Annual Sports Fest for all students, featuring a variety of sports events including basketball, volleyball, and track and field. Join to show your skills or cheer for your team!",
  },
  {
    id: 6,
    title: "Tech Symposium",
    location_id: 1,
    date: "2024-07-24",
    time: "10:00 AM - 4:00 PM",
    img: "https://images.pexels.com/photos/1181359/pexels-photo-1181359.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description:
      "A full-day symposium with expert speakers in the field of computer science. Topics include AI, cybersecurity, and software development. Network with tech enthusiasts and learn about the latest innovations.",
  },
  {
    id: 7,
    title: "Art Exhibition",
    location_id: 1,
    date: "2024-11-30",
    time: "9:00 AM - 5:00 PM",
    img: "https://images.pexels.com/photos/1126440/pexels-photo-1126440.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    description:
      "An art exhibition featuring works from students and local artists. Come and appreciate beautiful artworks, from paintings to sculptures, and meet the artists behind the creations.",
  },
];

export const currentUser = {
  name: "John Doe",
  email: "johndoe@example.com",
  password: "password123",
  user_id: 1,
};

export const reserveData = [
  {
    user_id: 1,
    location_id: 1,
    event_name: "Poster Making Contest",
    date: "2024-11-15",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    progress: "Approved",
  },
  {
    user_id: 2,
    location_id: 3,
    event_name: "Annual Tech Conference",
    date: "2024-11-20",
    startTime: "9:00 AM",
    endTime: "11:00 AM",
    progress: "Pending",
  },
  {
    user_id: 1,
    location_id: 4,
    event_name: "Coding Bootcamp",
    date: "2024-11-18",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    progress: "Approved",
  },
];
